### ISSUE TITLE
Rename this repo back to common-blockchain

### ISSUE THREAD

**Issue by weilu** [dcousens/common-blockchain#1]
... because this repo hosts the documentation of the common-blockchain APIs. Tests are like a bonus that comes with this repo. NPM module can stay as cb-tester. Perhaps you have other plans for common-blockchain?

**Comment by dcousens** [comment]
@weilu how would I go about that?

**Comment by weilu** [comment]
Duplicate the project only change the name in package.json

**Comment by dcousens** [comment]
cb-tester now resides at https://github.com/dcousens/cb-tester,  this module is now purely for changing the specification (README) and updating the `types.json` file which can be used for verification by modules if necessary.
