### ISSUE TITLE
Confirmations in Addresses.Transactions

### ISSUE THREAD

**Issue by CodersBrothers** [dcousens/common-blockchain#10]
I have this problem:
I need receive testcoins to new address (just created at instant as bridge) and instantly resend to other address but i need stay checking when transacction of first address is confirmated.

 Maybe will be cool see confirmations in transacctions history of address? Something like
```js
{
    txId: "c7736a0a0046d5a8cc61c8c3c2821d4d7517f5de2bc66a966011aaa79965ffba",
    txHex: "01000000011c1020c1114820e7c44e12e804aec5f4af1e8a6aad3c446c4cfc8aa53e61f73d010000008a47304402200fea124cecd36e92cb0b549b62740a26f374629b26f16292a3e858753035172802205ba172966addddbbe8181af6cd7fb6e9c53414fb6727c4f15589c74567e48ab30141040cfa3dfb357bdff37c8748c7771e173453da5d7caa32972ab2f5c888fff5bbaeb5fc812b473bf808206930fade81ef4e373e60039886b51022ce68902d96ef70ffffffff02204e0000000000001976a91461120f6e004c7a2e20ecdedf461f1eb032c2e5c388acabfb423d000000001976a91461b469ada61f37c620010912a9d5d56646015f1688ac00000000",
    blockId: "00000000000000001b701ecd0cf2b7a7742a320e9a06a506227ee345b5735d13",
    blockHeight: 318573,
    confirmations: 6
  }
```

Or, if is possible, how I will can do this with actual methods?

**Comment by dcousens** [comment]
@CodersBrothers hi! :)

Confirmations are subjective to the current blockHeight, so if you know that, you can just check what block height the node is at and then do `confirmations = currentBlockHeight - tx.blockHeight`.

**Comment by dcousens** [comment]
@CodersBrothers hi! :)

Confirmations are subjective to the current block height, so if you know that, you can just check what block height the node is at and then do `confirmations = tx.blockHeight - myBlockHeight`.

Here is some example code.

``` javascript
blockchain.blocks.latest(function(err, block) {
  if (err) ...

  var myHeight = block.blockHeight
  blockchain.transactions.get(txIds, function(err, results) {
    if (err) ...

    results.forEach(function(result) {
      result.confirmations = result.blockHeight - myHeight
    })

    // do something with results ...
  })
})
```

Hope that helps.

**Comment by CodersBrothers** [comment]
Interesting... subtracting height can determine confirmations. But this can works with double spent problems?

**Comment by dcousens** [comment]
@CodersBrothers of course?  If a block explorer were to give you a `confirmations` field, all they would be doing is the above for you.

Closing.
