### ISSUE TITLE
Blocks.Summary blockSize is bits?

### ISSUE THREAD

**Issue by fanatid** [dcousens/common-blockchain#12]
Why method `Blocks.Summary` return objects with `blockSize` instead `bits`?
In [cb-blockr](https://github.com/weilu/cb-blockr/blob/master/src/blocks.js#L57), [cb-chain](https://github.com/dcousens/cb-chain/blob/master/src/blocks.js#L38), [cb-helloblock](https://github.com/dcousens/cb-helloblock/blob/master/src/blocks.js#L29) this field is computed from bits property in response object.
It's very confusing...

**Comment by dcousens** [comment]
Thats a good point, and it has caught me out as well.
I'm happy to change it to `bits`, @weilu/@jprichardson?

The `block` aspect of the API is used less by our common uses cases, so I think it hasn't been as idiomatic as the rest.

**Comment by weilu** [comment]
`bits` works with me :)

**Comment by dcousens** [comment]
`Blocks.Summary` is going to be removed in `0.3.0`, since we are moving to only returning the headers hex for `Blocks.Get` and adding `Blocks.Transactions`, it would be superfluous.

**Comment by fanatid** [comment]
As I understand it's related with #9 ?

**Comment by dcousens** [comment]
@fanatid correct, I hope to have the `0.3.0` specification out soon so we can all start testing our code against it :)
