### ISSUE TITLE
Websocket Support

### ISSUE THREAD

**Issue by sidazhang** [dcousens/common-blockchain#2]
Reposting this in the correct repo

Websocket support is extremely useful for both client-side as well as server-side use cases. Every client side wallet almost always use WebSocket to get real time updates.

Most API providers also provide websocket support, since common-blockchain aims to provide a universal interface. Could this also add WebSocket support?

A example interface could be quite simple:

It only needs to support two interfaces as a min (this should cover 90% of use cases):

1. New-Transaction for addresses
2. New-Block

ping @weilu @dcousens @jprichardson

**Comment by dcousens** [comment]
See #13
