### ISSUE TITLE
Option to skip "tooManyAddresses"?

### ISSUE THREAD

**Issue by jprichardson** [dcousens/common-blockchain#3]
I'd like to make [cb-insight](https://github.com/jprichardson/cb-insight) use this package for its tests and common blockchain compatibility, but the `tooManyAddresses` kills the ability to use travis-ci because of the timeout. It'd be awesome to just pass an option to skip the `tooManyAddress` checking.

**Comment by dcousens** [comment]
@jprichardson I removed the hard coded timeouts in https://github.com/dcousens/common-blockchain/commit/c2360e4ac87b76194f0dcb671c415837f02fdb0f. 
Does this help?

**Comment by dcousens** [comment]
> It'd be awesome to be able to skip certain tests without resorting to mocha --grep....

Agree 100%.
Any ideas on how we can do that?

**Comment by dcousens** [comment]
Resolved by https://github.com/dcousens/common-blockchain/commit/c2360e4ac87b76194f0dcb671c415837f02fdb0f.  

>It'd be awesome to be able to skip certain tests without resorting to mocha --grep....

We should open another issue for this :)
