### ISSUE TITLE
Propagate return values

### ISSUE THREAD

**Issue by dcousens** [dcousens/common-blockchain#8]
As of `0.2.0` and https://github.com/dcousens/common-blockchain/commit/9434c1b49225dfe716eecd323333339976df27f8, I've enforced that `propagate` returns a `txId`.

The [current return format](https://github.com/dcousens/common-blockchain#transactionspropagate) is:
``` javascript
[
  "c7736a0a0046d5a8cc61c8c3c2821d4d7517f5de2bc66a966011aaa79965ffba",
  ...
]
```

However, perhaps the format adopted by @jprichardson in https://github.com/jprichardson/cb-insight#propagaterawtxs-callback is nicer.
I feel like it is important to have fidelity around which transactions failed to propagate, but I'm not sure what the API support is around this.

Thoughts? @weilu?

**edit:** in hindsight, I shouldn't have published `0.2.0` without having this discussion first.  But, we're sub `1.0.0` still.

**Comment by dcousens** [comment]
@jprichardson what is your thoughts on `[txId, ...]` vs `[{ txId: txId }, ...]`

**Comment by jprichardson** [comment]
> @jprichardson what is your thoughts on [txId, ...] vs [{ txId: txId }, ...]

I like `[{ txId: txId }, ...]` more. The only reason is that some APIs may return more properties about the transaction that could be included. At the moment, I'm not sure what that may be. Perhaps a `valid` flag? Not that it has to be required. Between the two, I'm not sure that it matters much, but overall `[{ txId: txId }, ...]` feels like more room for expansion without breaking compatibility.

**Comment by weilu** [comment]
I like arrays -- less verbose, easier to work with. As for extensibility, I can't think of a single thing at the moment. I'd rather do the minimum possible to satisfy our current needs than over-engineering based on what we could "possibly" need down the road. For `valid`, the array can just contain only the valid ones, so if one sees fewer transactions in response than request, they know they should find out which are invalid.

**Comment by dcousens** [comment]
>  The only reason is that some APIs may return more properties about the transaction that could be included

I don't think this is the case anywhere?  Do you have an example?  Not even bitcoind returns anything more?
The only real benefit to the `[{ txId: ... }, ...]` model that I can see is error handling, but at this point there is no API support for that anywhere, so might as well ignore it.

**Comment by jprichardson** [comment]
> I like arrays -- less verbose, easier to work with. As for extensibility, I can't think of a single thing at the moment. I'd rather do the minimum possible to satisfy our current needs than over-engineering based on what we could "possibly" need down the road.

Excellent point @weilu

**Comment by dcousens** [comment]
After a discussion with @rubensayshi I think we should just remove the batched version of this end point entirely.

There is too much fine grained control needed, and as evidenced, we're omitting potentially useful information by allowing it to be batched.

**Comment by dcousens** [comment]
Closing in favour of removing the batch end point for `propagation`.
