### ISSUE TITLE
Rework Blocks.Get and remove Blocks.Summary

### ISSUE THREAD

**Issue by dcousens** [dcousens/common-blockchain#9]
**Problem**: There is no definitive way to order transactions in a block, and as such the existence of returning the "full" hex is mostly pointless.   The hex cannot be verified without decoding.

**Proposal**: Remove `Blocks.Summary`, and for `Blocks.Get` return the following:

``` javascript
{
  "blockId": "00000000000000001b701ecd0cf2b7a7742a320e9a06a506227ee345b5735d13",
  "blockHeight": 318573,
  "blockHex": "020000003bef0d0b88737698572aa5c78 ... headers only ... much hex",
  "txCount": 236
}
```

This would then be consistent with `Transactions.Get`.

Another end point could then be added `Blocks.Transactions` which would return:

``` javascript
[
  {
    txId: "c7736a0a0046d5a8cc61c8c3c2821d4d7517f5de2bc66a966011aaa79965ffba",
    txHex: "01000000011c1020c1114820e7c44e12e804aec5f4af1e8a6aad3c446c4cfc8aa53e61f73d010000008a47304402200fea124cecd36e92cb0b549b62740a26f374629b26f16292a3e858753035172802205ba172966addddbbe8181af6cd7fb6e9c53414fb6727c4f15589c74567e48ab30141040cfa3dfb357bdff37c8748c7771e173453da5d7caa32972ab2f5c888fff5bbaeb5fc812b473bf808206930fade81ef4e373e60039886b51022ce68902d96ef70ffffffff02204e0000000000001976a91461120f6e004c7a2e20ecdedf461f1eb032c2e5c388acabfb423d000000001976a91461b469ada61f37c620010912a9d5d56646015f1688ac00000000",
    blockId: "00000000000000001b701ecd0cf2b7a7742a320e9a06a506227ee345b5735d13",
    blockHeight: 318573
  },
  ...
]
```

**Comment by dcousens** [comment]
@weilu thoughts?

**Comment by dcousens** [comment]
I feel this API proposal would be more consistent and is definitely more testable.

**Comment by dcousens** [comment]
@jprichardson thoughts?

**Comment by dcousens** [comment]
https://github.com/dcousens/common-blockchain/commit/2651f7479ea7c7fc4ef71a2637ebef038ead9551 is the reason why this change will be useful.   We can only verify headers.

**Comment by weilu** [comment]
I'm happy with this. More consistent indeed
